apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: fintech-backend
spec:
  type: LoadBalancer  # <-- Add this line
  selector:
    app: fintech-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080