apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: fintech-frontend
spec:
  type: LoadBalancer
  selector:
    app: fintech-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80